# Generated by Django 4.1.1 on 2022-09-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bib_graphql', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='titel',
        ),
    ]
