# Generated by Django 4.1.1 on 2022-09-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bib_graphql', '0002_rename_title_book_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
